import{a as L,i as p,S as v}from"./assets/vendor-DEenWwFD.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const q="48188433-e0448b24de47b1903ec6a4bb7",h=(r,e)=>{const s={params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}};return L.get("https://pixabay.com/api/",s)},f=r=>r.map(({webformatURL:e,largeImageURL:s,tags:l,likes:t,views:o,comments:i,downloads:b})=>`<a href="${s}" class="gallery-item">
  <div class="photo-card">
  <img src="${e}" alt="${l}" loading="lazy" width="360" />
  <div class="photo-info">
    <p class="photo-info-item">Likes<span>${t}</span></p>
	<p class="photo-info-item">Views<span>${o}</span></p>
	<p class="photo-info-item">Comments<span>${i}</span></p>
	<p class="photo-info-item">Downloads<span>${b}</span></p>
  </div>
  </div>
  </a>`).join(""),y=document.querySelector(".form-search"),u=document.querySelector(".gallery"),c=document.querySelector(".loader"),n=document.querySelector(".load-more-btn");let a=1,d="",m;c.style.display="none";const w=async r=>{try{if(r.preventDefault(),u.innerHTML="",c.style.display="block",d=r.currentTarget.elements.user_query.value.trim(),d===""){p.warning({title:"Warning",position:"topRight",message:"Please enter a search query!"});return}a=1,n.classList.add("is-hidden");const{data:e}=await h(d,a);if(c.style.display="none",!e.hits.length){p.error({title:"Error",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=f(e.hits);u.insertAdjacentHTML("beforeend",s),m=new v(".gallery-item",{captions:!0,captionsData:"alt",captionDelay:250}),m.refresh(),y.reset(),e.totalHits>1&&(n.classList.remove("is-hidden"),n.addEventListener("click",g))}catch{c.style.display="none"}};y.addEventListener("submit",w);const g=async r=>{try{a++;const{data:e}=await h(d,a),s=f(e.hits);u.insertAdjacentHTML("beforeend",s),m.refresh(),a*15>=e.totalHits&&(p.info({title:"Info",position:"topRight",message:"We're sorry, but you've reached the end of search results."}),n.classList.add("is-hidden"),n.removeEventListener("click",g)),P()}catch(e){p.error({title:"Error",position:"topRight",message:"Failed to load images. Please try again later."}),console.log(e)}},P=()=>{const{height:r}=document.galleryContainer.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
